# Name
name: build_countingbook_app

# trigger
on:
    - push

jobs:
    build_app:
      runs-on: ubuntu_latest
      steps:
      - id: s01
        run: echo "github ${{ github.ref_name }}"
      # Setup the environment
      - id: s02
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - id: s03
        uses: actions/checkout@v5
      - run: ls -la